# Copyright (C) The c-ares project and its contributors
# SPDX-License-Identifier: MIT
name: OpenWatcom
on:
  push:
    branches:
      - main
    pull_request:
      types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: open-watcom/setup-watcom@v0
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: configure
        run: |
          copy /Y include\ares_build.h.dist include\ares_build.h
      - name: Build c-ares
        run: |
          wmake -u -f Makefile.Watcom
      - name: distclean
        run: |
          wmake -u -f Makefile.Watcom clean

